vich_uploader:
    db_driver: orm
    mappings:
        user_image:
            uri_prefix: '%AVATAR_BASEPATH%'
            upload_destination: '%kernel.project_dir%/public/%AVATAR_BASEPATH%'
            namer:
                service: vich_uploader.namer_hash
                options: { algorithm: 'md5' }
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        product_image:
            uri_prefix: '%app.path.product_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.product_image%'
            namer:
                service: vich_uploader.namer_hash
                options: { algorithm: 'md5' }
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            
        application_logo:
            uri_prefix: '%app.path.application_logo%'
            upload_destination: '%kernel.project_dir%/public%app.path.application_logo%'
            namer:
                service: vich_uploader.namer_hash
                options: { algorithm: 'md5' }
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
